[package]
name = "visibility-calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
sgp4 = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
anyhow = "1.0"
