name: Performance Benchmark

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  benchmark:
    name: Run Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build test runner
        working-directory: test-runner
        run: cargo build --release

      - name: Discover implementations
        id: discover
        working-directory: test-runner
        run: |
          cargo run --release -- discover | tee implementations.txt

      - name: Build all Docker images
        working-directory: test-runner
        run: |
          cargo run --release -- build

      - name: Run benchmark
        working-directory: test-runner
        run: |
          echo "# Performance Benchmark Results" > benchmark-results.md
          echo "" >> benchmark-results.md
          echo "**Date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> benchmark-results.md
          echo "**Commit:** ${{ github.sha }}" >> benchmark-results.md
          echo "" >> benchmark-results.md

          # Run all implementations and capture timing
          cargo run --release -- run 2>&1 | tee benchmark-output.log

          # Extract summary
          echo "## Execution Times" >> benchmark-results.md
          echo "" >> benchmark-results.md
          echo "| Implementation | Time |" >> benchmark-results.md
          echo "|----------------|------|" >> benchmark-results.md

          grep "✓.*-.*s$" benchmark-output.log | while read line; do
            impl=$(echo "$line" | awk '{print $2}')
            time=$(echo "$line" | awk '{print $NF}')
            echo "| $impl | $time |" >> benchmark-results.md
          done

          echo "" >> benchmark-results.md
          echo "---" >> benchmark-results.md
          echo "*Generated by GitHub Actions*" >> benchmark-results.md

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: |
            test-runner/benchmark-results.md
            test-runner/benchmark-output.log
          retention-days: 90

      - name: Post to summary
        run: |
          cat test-runner/benchmark-results.md >> $GITHUB_STEP_SUMMARY

      - name: Check for performance regression
        run: |
          # Simple check: fail if any implementation takes > 60s
          if grep -E "✓.*-.*[6-9][0-9]\.[0-9]+s" test-runner/benchmark-output.log; then
            echo "⚠️ Performance regression detected (implementation taking >60s)"
            exit 1
          fi

          # Check if python-skyfield takes >40s (it should be ~22-30s)
          if grep "python-skyfield.*[4-9][0-9]\.[0-9]+s" test-runner/benchmark-output.log; then
            echo "⚠️ Python-skyfield performance regression (>40s)"
            exit 1
          fi

          echo "✓ No performance regressions detected"
